//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SisVentaDevExpress.Ventas
{

    [Persistent(@"articulo")]
    public partial class Articulo : XPLiteObject
    {
        int fIdArticulos;
        [Key(true)]
        [Persistent(@"idArticulos")]
        public int IdArticulos
        {
            get { return fIdArticulos; }
            set { SetPropertyValue<int>(nameof(IdArticulos), ref fIdArticulos, value); }
        }
        string fCodigo;
        [Size(50)]
        public string Codigo
        {
            get { return fCodigo; }
            set { SetPropertyValue<string>(nameof(Codigo), ref fCodigo, value); }
        }
        string fNombre;
        [Size(50)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDescripcion;
        [Size(1024)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        Categoria fIdCategoria;
        [Persistent(@"idCategoria")]
        [Association(@"ArticuloReferencesCategoria")]
        public Categoria IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<Categoria>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        Presentacion fIdPresentacion;
        [Association(@"ArticuloReferencesPresentacion")]
        public Presentacion IdPresentacion
        {
            get { return fIdPresentacion; }
            set { SetPropertyValue<Presentacion>(nameof(IdPresentacion), ref fIdPresentacion, value); }
        }
        decimal fPrecioVenta;
        public decimal PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<decimal>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        [Association(@"Detalle_IngresoReferencesArticulo")]
        public XPCollection<Detalle_Ingreso> Detalle_Ingresos { get { return GetCollection<Detalle_Ingreso>(nameof(Detalle_Ingresos)); } }
    }

}
