//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SisVentaDevExpress.Ventas
{

    [Persistent(@"categoria")]
    public partial class Categoria : XPLiteObject
    {
        int fIdCategoria;
        [Key(true)]
        [Persistent(@"idCategoria")]
        public int IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<int>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        string fNombre;
        [Size(50)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDescripcion;
        [Size(256)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        [Association(@"ArticuloReferencesCategoria")]
        public XPCollection<Articulo> Articuloes { get { return GetCollection<Articulo>(nameof(Articuloes)); } }
    }

}
