//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SisVentaDevExpress.Ventas
{

    [Persistent(@"cliente")]
    public partial class Cliente : XPLiteObject
    {
        int fIdCliente;
        [Key(true)]
        [Persistent(@"idCliente")]
        public int IdCliente
        {
            get { return fIdCliente; }
            set { SetPropertyValue<int>(nameof(IdCliente), ref fIdCliente, value); }
        }
        string fNombre;
        [Size(50)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fApellido;
        [Size(50)]
        public string Apellido
        {
            get { return fApellido; }
            set { SetPropertyValue<string>(nameof(Apellido), ref fApellido, value); }
        }
        string fSexo;
        [Size(20)]
        public string Sexo
        {
            get { return fSexo; }
            set { SetPropertyValue<string>(nameof(Sexo), ref fSexo, value); }
        }
        DateTime fFecha_Nacimiento;
        public DateTime Fecha_Nacimiento
        {
            get { return fFecha_Nacimiento; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_Nacimiento), ref fFecha_Nacimiento, value); }
        }
        string fTipo_Documento;
        [Size(50)]
        public string Tipo_Documento
        {
            get { return fTipo_Documento; }
            set { SetPropertyValue<string>(nameof(Tipo_Documento), ref fTipo_Documento, value); }
        }
        string fNum_Documento;
        [Size(50)]
        public string Num_Documento
        {
            get { return fNum_Documento; }
            set { SetPropertyValue<string>(nameof(Num_Documento), ref fNum_Documento, value); }
        }
        string fDireccion;
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fTelefono;
        [Size(20)]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        [Association(@"VentaReferencesCliente")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
