//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SisVentaDevExpress.Ventas
{

    [Persistent(@"detalle_venta")]
    public partial class Detalle_venta : XPLiteObject
    {
        int fIdDetalle_Venta;
        [Key(true)]
        [Persistent(@"idDetalle_Venta")]
        public int IdDetalle_Venta
        {
            get { return fIdDetalle_Venta; }
            set { SetPropertyValue<int>(nameof(IdDetalle_Venta), ref fIdDetalle_Venta, value); }
        }
        Venta fIdVenta;
        [Association(@"Detalle_ventaReferencesVenta")]
        public Venta IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<Venta>(nameof(IdVenta), ref fIdVenta, value); }
        }
        Detalle_Ingreso fIdDetalle_Ingreso;
        [Persistent(@"idDetalle_Ingreso")]
        [Association(@"Detalle_ventaReferencesDetalle_Ingreso")]
        public Detalle_Ingreso IdDetalle_Ingreso
        {
            get { return fIdDetalle_Ingreso; }
            set { SetPropertyValue<Detalle_Ingreso>(nameof(IdDetalle_Ingreso), ref fIdDetalle_Ingreso, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fPrecio_Venta;
        public decimal Precio_Venta
        {
            get { return fPrecio_Venta; }
            set { SetPropertyValue<decimal>(nameof(Precio_Venta), ref fPrecio_Venta, value); }
        }
        decimal fDescuento;
        public decimal Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<decimal>(nameof(Descuento), ref fDescuento, value); }
        }
    }

}
