//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SisVentaDevExpress.Ventas
{

    [Persistent(@"detalle_venta")]
    public partial class Detalle_venta : XPLiteObject
    {
        int fIdDetalle_Venta;
        [Key(true)]
        [Persistent(@"idDetalle_Venta")]
        public int IdDetalle_Venta
        {
            get { return fIdDetalle_Venta; }
            set { SetPropertyValue<int>(nameof(IdDetalle_Venta), ref fIdDetalle_Venta, value); }
        }
        Venta fIdVenta;
        [Association(@"Detalle_ventaReferencesVenta")]
        public Venta IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<Venta>(nameof(IdVenta), ref fIdVenta, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fPrecio_Venta;
        public decimal Precio_Venta
        {
            get { return fPrecio_Venta; }
            set { SetPropertyValue<decimal>(nameof(Precio_Venta), ref fPrecio_Venta, value); }
        }
        decimal fDescuento;
        public decimal Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<decimal>(nameof(Descuento), ref fDescuento, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        Articulo fIdArticulo;
        [Persistent(@"idArticulo")]
        [Association(@"Detalle_ventaReferencesArticulo")]
        public Articulo IdArticulo
        {
            get { return fIdArticulo; }
            set { SetPropertyValue<Articulo>(nameof(IdArticulo), ref fIdArticulo, value); }
        }
        decimal fSubTotal;
        public decimal SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<decimal>(nameof(SubTotal), ref fSubTotal, value); }
        }
        decimal fIVA;
        public decimal IVA
        {
            get { return fIVA; }
            set { SetPropertyValue<decimal>(nameof(IVA), ref fIVA, value); }
        }
        int fDescuentoP;
        public int DescuentoP
        {
            get { return fDescuentoP; }
            set { SetPropertyValue<int>(nameof(DescuentoP), ref fDescuentoP, value); }
        }
    }

}
