//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SisVentaDevExpress.Ventas
{

    [Persistent(@"ingreso")]
    public partial class Ingreso : XPLiteObject
    {
        int fIdIngreso;
        [Key(true)]
        [Persistent(@"idIngreso")]
        public int IdIngreso
        {
            get { return fIdIngreso; }
            set { SetPropertyValue<int>(nameof(IdIngreso), ref fIdIngreso, value); }
        }
        Trabajador fIdTrabajador;
        [Persistent(@"idTrabajador")]
        [Association(@"IngresoReferencesTrabajador")]
        public Trabajador IdTrabajador
        {
            get { return fIdTrabajador; }
            set { SetPropertyValue<Trabajador>(nameof(IdTrabajador), ref fIdTrabajador, value); }
        }
        Proveedor fIdProveedor;
        [Persistent(@"idProveedor")]
        [Association(@"IngresoReferencesProveedor")]
        public Proveedor IdProveedor
        {
            get { return fIdProveedor; }
            set { SetPropertyValue<Proveedor>(nameof(IdProveedor), ref fIdProveedor, value); }
        }
        DateTime fFecha_Ingreso;
        public DateTime Fecha_Ingreso
        {
            get { return fFecha_Ingreso; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_Ingreso), ref fFecha_Ingreso, value); }
        }
        string fTipo_Comprobante;
        [Size(50)]
        public string Tipo_Comprobante
        {
            get { return fTipo_Comprobante; }
            set { SetPropertyValue<string>(nameof(Tipo_Comprobante), ref fTipo_Comprobante, value); }
        }
        string fSerie;
        [Size(10)]
        public string Serie
        {
            get { return fSerie; }
            set { SetPropertyValue<string>(nameof(Serie), ref fSerie, value); }
        }
        string fNDocumento;
        [Size(10)]
        public string NDocumento
        {
            get { return fNDocumento; }
            set { SetPropertyValue<string>(nameof(NDocumento), ref fNDocumento, value); }
        }
        decimal fIVA;
        public decimal IVA
        {
            get { return fIVA; }
            set { SetPropertyValue<decimal>(nameof(IVA), ref fIVA, value); }
        }
        decimal fTotal_Invercion;
        public decimal Total_Invercion
        {
            get { return fTotal_Invercion; }
            set { SetPropertyValue<decimal>(nameof(Total_Invercion), ref fTotal_Invercion, value); }
        }
        decimal fSub_total;
        public decimal Sub_total
        {
            get { return fSub_total; }
            set { SetPropertyValue<decimal>(nameof(Sub_total), ref fSub_total, value); }
        }
        [Association(@"Detalle_IngresoReferencesIngreso")]
        public XPCollection<Detalle_Ingreso> Detalle_Ingresos { get { return GetCollection<Detalle_Ingreso>(nameof(Detalle_Ingresos)); } }
    }

}
